var wms_layers = [];

var format_Vereinfacht_0 = new ol.format.GeoJSON();
var features_Vereinfacht_0 = format_Vereinfacht_0.readFeatures(json_Vereinfacht_0, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Vereinfacht_0 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Vereinfacht_0.addFeatures(features_Vereinfacht_0);
var lyr_Vereinfacht_0 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_Vereinfacht_0, 
                style: style_Vereinfacht_0,
                interactive: true,
    title: 'Vereinfacht<br />\
    <img src="styles/legend/Vereinfacht_0_0.png" /> Afghanistan<br />\
    <img src="styles/legend/Vereinfacht_0_1.png" /> Akrotiri Sovereign Base Area<br />\
    <img src="styles/legend/Vereinfacht_0_2.png" /> Aland<br />\
    <img src="styles/legend/Vereinfacht_0_3.png" /> Albania<br />\
    <img src="styles/legend/Vereinfacht_0_4.png" /> Algeria<br />\
    <img src="styles/legend/Vereinfacht_0_5.png" /> American Samoa<br />\
    <img src="styles/legend/Vereinfacht_0_6.png" /> Andorra<br />\
    <img src="styles/legend/Vereinfacht_0_7.png" /> Angola<br />\
    <img src="styles/legend/Vereinfacht_0_8.png" /> Anguilla<br />\
    <img src="styles/legend/Vereinfacht_0_9.png" /> Antarctica<br />\
    <img src="styles/legend/Vereinfacht_0_10.png" /> Antigua and Barbuda<br />\
    <img src="styles/legend/Vereinfacht_0_11.png" /> Argentina<br />\
    <img src="styles/legend/Vereinfacht_0_12.png" /> Armenia<br />\
    <img src="styles/legend/Vereinfacht_0_13.png" /> Aruba<br />\
    <img src="styles/legend/Vereinfacht_0_14.png" /> Ashmore and Cartier Islands<br />\
    <img src="styles/legend/Vereinfacht_0_15.png" /> Australia<br />\
    <img src="styles/legend/Vereinfacht_0_16.png" /> Austria<br />\
    <img src="styles/legend/Vereinfacht_0_17.png" /> Azerbaijan<br />\
    <img src="styles/legend/Vereinfacht_0_18.png" /> Bahrain<br />\
    <img src="styles/legend/Vereinfacht_0_19.png" /> Bajo Nuevo Bank (Petrel Is.)<br />\
    <img src="styles/legend/Vereinfacht_0_20.png" /> Bangladesh<br />\
    <img src="styles/legend/Vereinfacht_0_21.png" /> Barbados<br />\
    <img src="styles/legend/Vereinfacht_0_22.png" /> Baykonur Cosmodrome<br />\
    <img src="styles/legend/Vereinfacht_0_23.png" /> Belarus<br />\
    <img src="styles/legend/Vereinfacht_0_24.png" /> Belgium<br />\
    <img src="styles/legend/Vereinfacht_0_25.png" /> Belize<br />\
    <img src="styles/legend/Vereinfacht_0_26.png" /> Benin<br />\
    <img src="styles/legend/Vereinfacht_0_27.png" /> Bermuda<br />\
    <img src="styles/legend/Vereinfacht_0_28.png" /> Bhutan<br />\
    <img src="styles/legend/Vereinfacht_0_29.png" /> Bolivia<br />\
    <img src="styles/legend/Vereinfacht_0_30.png" /> Bosnia and Herzegovina<br />\
    <img src="styles/legend/Vereinfacht_0_31.png" /> Botswana<br />\
    <img src="styles/legend/Vereinfacht_0_32.png" /> Brazil<br />\
    <img src="styles/legend/Vereinfacht_0_33.png" /> British Indian Ocean Territory<br />\
    <img src="styles/legend/Vereinfacht_0_34.png" /> British Virgin Islands<br />\
    <img src="styles/legend/Vereinfacht_0_35.png" /> Brunei<br />\
    <img src="styles/legend/Vereinfacht_0_36.png" /> Bulgaria<br />\
    <img src="styles/legend/Vereinfacht_0_37.png" /> Burkina Faso<br />\
    <img src="styles/legend/Vereinfacht_0_38.png" /> Burundi<br />\
    <img src="styles/legend/Vereinfacht_0_39.png" /> Cambodia<br />\
    <img src="styles/legend/Vereinfacht_0_40.png" /> Cameroon<br />\
    <img src="styles/legend/Vereinfacht_0_41.png" /> Canada<br />\
    <img src="styles/legend/Vereinfacht_0_42.png" /> Cape Verde<br />\
    <img src="styles/legend/Vereinfacht_0_43.png" /> Cayman Islands<br />\
    <img src="styles/legend/Vereinfacht_0_44.png" /> Central African Republic<br />\
    <img src="styles/legend/Vereinfacht_0_45.png" /> Chad<br />\
    <img src="styles/legend/Vereinfacht_0_46.png" /> Chile<br />\
    <img src="styles/legend/Vereinfacht_0_47.png" /> China<br />\
    <img src="styles/legend/Vereinfacht_0_48.png" /> Clipperton Island<br />\
    <img src="styles/legend/Vereinfacht_0_49.png" /> Colombia<br />\
    <img src="styles/legend/Vereinfacht_0_50.png" /> Comoros<br />\
    <img src="styles/legend/Vereinfacht_0_51.png" /> Cook Islands<br />\
    <img src="styles/legend/Vereinfacht_0_52.png" /> Coral Sea Islands<br />\
    <img src="styles/legend/Vereinfacht_0_53.png" /> Costa Rica<br />\
    <img src="styles/legend/Vereinfacht_0_54.png" /> Croatia<br />\
    <img src="styles/legend/Vereinfacht_0_55.png" /> Cuba<br />\
    <img src="styles/legend/Vereinfacht_0_56.png" /> Curaçao<br />\
    <img src="styles/legend/Vereinfacht_0_57.png" /> Cyprus<br />\
    <img src="styles/legend/Vereinfacht_0_58.png" /> Cyprus No Mans Area<br />\
    <img src="styles/legend/Vereinfacht_0_59.png" /> Czech Republic<br />\
    <img src="styles/legend/Vereinfacht_0_60.png" /> Democratic Republic of the Congo<br />\
    <img src="styles/legend/Vereinfacht_0_61.png" /> Denmark<br />\
    <img src="styles/legend/Vereinfacht_0_62.png" /> Dhekelia Sovereign Base Area<br />\
    <img src="styles/legend/Vereinfacht_0_63.png" /> Djibouti<br />\
    <img src="styles/legend/Vereinfacht_0_64.png" /> Dominica<br />\
    <img src="styles/legend/Vereinfacht_0_65.png" /> Dominican Republic<br />\
    <img src="styles/legend/Vereinfacht_0_66.png" /> East Timor<br />\
    <img src="styles/legend/Vereinfacht_0_67.png" /> Ecuador<br />\
    <img src="styles/legend/Vereinfacht_0_68.png" /> Egypt<br />\
    <img src="styles/legend/Vereinfacht_0_69.png" /> El Salvador<br />\
    <img src="styles/legend/Vereinfacht_0_70.png" /> Equatorial Guinea<br />\
    <img src="styles/legend/Vereinfacht_0_71.png" /> Eritrea<br />\
    <img src="styles/legend/Vereinfacht_0_72.png" /> Estonia<br />\
    <img src="styles/legend/Vereinfacht_0_73.png" /> Ethiopia<br />\
    <img src="styles/legend/Vereinfacht_0_74.png" /> Falkland Islands<br />\
    <img src="styles/legend/Vereinfacht_0_75.png" /> Faroe Islands<br />\
    <img src="styles/legend/Vereinfacht_0_76.png" /> Federated States of Micronesia<br />\
    <img src="styles/legend/Vereinfacht_0_77.png" /> Fiji<br />\
    <img src="styles/legend/Vereinfacht_0_78.png" /> Finland<br />\
    <img src="styles/legend/Vereinfacht_0_79.png" /> France<br />\
    <img src="styles/legend/Vereinfacht_0_80.png" /> French Polynesia<br />\
    <img src="styles/legend/Vereinfacht_0_81.png" /> French Southern and Antarctic Lands<br />\
    <img src="styles/legend/Vereinfacht_0_82.png" /> Gabon<br />\
    <img src="styles/legend/Vereinfacht_0_83.png" /> Gambia<br />\
    <img src="styles/legend/Vereinfacht_0_84.png" /> Georgia<br />\
    <img src="styles/legend/Vereinfacht_0_85.png" /> Germany<br />\
    <img src="styles/legend/Vereinfacht_0_86.png" /> Ghana<br />\
    <img src="styles/legend/Vereinfacht_0_87.png" /> Gibraltar<br />\
    <img src="styles/legend/Vereinfacht_0_88.png" /> Greece<br />\
    <img src="styles/legend/Vereinfacht_0_89.png" /> Greenland<br />\
    <img src="styles/legend/Vereinfacht_0_90.png" /> Grenada<br />\
    <img src="styles/legend/Vereinfacht_0_91.png" /> Guam<br />\
    <img src="styles/legend/Vereinfacht_0_92.png" /> Guatemala<br />\
    <img src="styles/legend/Vereinfacht_0_93.png" /> Guernsey<br />\
    <img src="styles/legend/Vereinfacht_0_94.png" /> Guinea<br />\
    <img src="styles/legend/Vereinfacht_0_95.png" /> Guinea Bissau<br />\
    <img src="styles/legend/Vereinfacht_0_96.png" /> Guyana<br />\
    <img src="styles/legend/Vereinfacht_0_97.png" /> Haiti<br />\
    <img src="styles/legend/Vereinfacht_0_98.png" /> Heard Island and McDonald Islands<br />\
    <img src="styles/legend/Vereinfacht_0_99.png" /> Honduras<br />\
    <img src="styles/legend/Vereinfacht_0_100.png" /> Hong Kong S.A.R.<br />\
    <img src="styles/legend/Vereinfacht_0_101.png" /> Hungary<br />\
    <img src="styles/legend/Vereinfacht_0_102.png" /> Iceland<br />\
    <img src="styles/legend/Vereinfacht_0_103.png" /> India<br />\
    <img src="styles/legend/Vereinfacht_0_104.png" /> Indian Ocean Territories<br />\
    <img src="styles/legend/Vereinfacht_0_105.png" /> Indonesia<br />\
    <img src="styles/legend/Vereinfacht_0_106.png" /> Iran<br />\
    <img src="styles/legend/Vereinfacht_0_107.png" /> Iraq<br />\
    <img src="styles/legend/Vereinfacht_0_108.png" /> Ireland<br />\
    <img src="styles/legend/Vereinfacht_0_109.png" /> Isle of Man<br />\
    <img src="styles/legend/Vereinfacht_0_110.png" /> Israel<br />\
    <img src="styles/legend/Vereinfacht_0_111.png" /> Italy<br />\
    <img src="styles/legend/Vereinfacht_0_112.png" /> Ivory Coast<br />\
    <img src="styles/legend/Vereinfacht_0_113.png" /> Jamaica<br />\
    <img src="styles/legend/Vereinfacht_0_114.png" /> Japan<br />\
    <img src="styles/legend/Vereinfacht_0_115.png" /> Jersey<br />\
    <img src="styles/legend/Vereinfacht_0_116.png" /> Jordan<br />\
    <img src="styles/legend/Vereinfacht_0_117.png" /> Kazakhstan<br />\
    <img src="styles/legend/Vereinfacht_0_118.png" /> Kenya<br />\
    <img src="styles/legend/Vereinfacht_0_119.png" /> Kiribati<br />\
    <img src="styles/legend/Vereinfacht_0_120.png" /> Kosovo<br />\
    <img src="styles/legend/Vereinfacht_0_121.png" /> Kuwait<br />\
    <img src="styles/legend/Vereinfacht_0_122.png" /> Kyrgyzstan<br />\
    <img src="styles/legend/Vereinfacht_0_123.png" /> Laos<br />\
    <img src="styles/legend/Vereinfacht_0_124.png" /> Latvia<br />\
    <img src="styles/legend/Vereinfacht_0_125.png" /> Lebanon<br />\
    <img src="styles/legend/Vereinfacht_0_126.png" /> Lesotho<br />\
    <img src="styles/legend/Vereinfacht_0_127.png" /> Liberia<br />\
    <img src="styles/legend/Vereinfacht_0_128.png" /> Libya<br />\
    <img src="styles/legend/Vereinfacht_0_129.png" /> Liechtenstein<br />\
    <img src="styles/legend/Vereinfacht_0_130.png" /> Lithuania<br />\
    <img src="styles/legend/Vereinfacht_0_131.png" /> Luxembourg<br />\
    <img src="styles/legend/Vereinfacht_0_132.png" /> Macao S.A.R<br />\
    <img src="styles/legend/Vereinfacht_0_133.png" /> Macedonia<br />\
    <img src="styles/legend/Vereinfacht_0_134.png" /> Madagascar<br />\
    <img src="styles/legend/Vereinfacht_0_135.png" /> Malawi<br />\
    <img src="styles/legend/Vereinfacht_0_136.png" /> Malaysia<br />\
    <img src="styles/legend/Vereinfacht_0_137.png" /> Maldives<br />\
    <img src="styles/legend/Vereinfacht_0_138.png" /> Mali<br />\
    <img src="styles/legend/Vereinfacht_0_139.png" /> Malta<br />\
    <img src="styles/legend/Vereinfacht_0_140.png" /> Marshall Islands<br />\
    <img src="styles/legend/Vereinfacht_0_141.png" /> Mauritania<br />\
    <img src="styles/legend/Vereinfacht_0_142.png" /> Mauritius<br />\
    <img src="styles/legend/Vereinfacht_0_143.png" /> Mexico<br />\
    <img src="styles/legend/Vereinfacht_0_144.png" /> Moldova<br />\
    <img src="styles/legend/Vereinfacht_0_145.png" /> Monaco<br />\
    <img src="styles/legend/Vereinfacht_0_146.png" /> Mongolia<br />\
    <img src="styles/legend/Vereinfacht_0_147.png" /> Montenegro<br />\
    <img src="styles/legend/Vereinfacht_0_148.png" /> Montserrat<br />\
    <img src="styles/legend/Vereinfacht_0_149.png" /> Morocco<br />\
    <img src="styles/legend/Vereinfacht_0_150.png" /> Mozambique<br />\
    <img src="styles/legend/Vereinfacht_0_151.png" /> Myanmar<br />\
    <img src="styles/legend/Vereinfacht_0_152.png" /> Namibia<br />\
    <img src="styles/legend/Vereinfacht_0_153.png" /> Nauru<br />\
    <img src="styles/legend/Vereinfacht_0_154.png" /> Nepal<br />\
    <img src="styles/legend/Vereinfacht_0_155.png" /> Netherlands<br />\
    <img src="styles/legend/Vereinfacht_0_156.png" /> New Caledonia<br />\
    <img src="styles/legend/Vereinfacht_0_157.png" /> New Zealand<br />\
    <img src="styles/legend/Vereinfacht_0_158.png" /> Nicaragua<br />\
    <img src="styles/legend/Vereinfacht_0_159.png" /> Niger<br />\
    <img src="styles/legend/Vereinfacht_0_160.png" /> Nigeria<br />\
    <img src="styles/legend/Vereinfacht_0_161.png" /> Niue<br />\
    <img src="styles/legend/Vereinfacht_0_162.png" /> Norfolk Island<br />\
    <img src="styles/legend/Vereinfacht_0_163.png" /> North Korea<br />\
    <img src="styles/legend/Vereinfacht_0_164.png" /> Northern Cyprus<br />\
    <img src="styles/legend/Vereinfacht_0_165.png" /> Northern Mariana Islands<br />\
    <img src="styles/legend/Vereinfacht_0_166.png" /> Norway<br />\
    <img src="styles/legend/Vereinfacht_0_167.png" /> Oman<br />\
    <img src="styles/legend/Vereinfacht_0_168.png" /> Pakistan<br />\
    <img src="styles/legend/Vereinfacht_0_169.png" /> Palau<br />\
    <img src="styles/legend/Vereinfacht_0_170.png" /> Palestine<br />\
    <img src="styles/legend/Vereinfacht_0_171.png" /> Panama<br />\
    <img src="styles/legend/Vereinfacht_0_172.png" /> Papua New Guinea<br />\
    <img src="styles/legend/Vereinfacht_0_173.png" /> Paraguay<br />\
    <img src="styles/legend/Vereinfacht_0_174.png" /> Peru<br />\
    <img src="styles/legend/Vereinfacht_0_175.png" /> Philippines<br />\
    <img src="styles/legend/Vereinfacht_0_176.png" /> Pitcairn Islands<br />\
    <img src="styles/legend/Vereinfacht_0_177.png" /> Poland<br />\
    <img src="styles/legend/Vereinfacht_0_178.png" /> Portugal<br />\
    <img src="styles/legend/Vereinfacht_0_179.png" /> Puerto Rico<br />\
    <img src="styles/legend/Vereinfacht_0_180.png" /> Qatar<br />\
    <img src="styles/legend/Vereinfacht_0_181.png" /> Republic of Congo<br />\
    <img src="styles/legend/Vereinfacht_0_182.png" /> Republic of Serbia<br />\
    <img src="styles/legend/Vereinfacht_0_183.png" /> Romania<br />\
    <img src="styles/legend/Vereinfacht_0_184.png" /> Russia<br />\
    <img src="styles/legend/Vereinfacht_0_185.png" /> Rwanda<br />\
    <img src="styles/legend/Vereinfacht_0_186.png" /> Saint Barthelemy<br />\
    <img src="styles/legend/Vereinfacht_0_187.png" /> Saint Helena<br />\
    <img src="styles/legend/Vereinfacht_0_188.png" /> Saint Kitts and Nevis<br />\
    <img src="styles/legend/Vereinfacht_0_189.png" /> Saint Lucia<br />\
    <img src="styles/legend/Vereinfacht_0_190.png" /> Saint Martin<br />\
    <img src="styles/legend/Vereinfacht_0_191.png" /> Saint Pierre and Miquelon<br />\
    <img src="styles/legend/Vereinfacht_0_192.png" /> Saint Vincent and the Grenadines<br />\
    <img src="styles/legend/Vereinfacht_0_193.png" /> Samoa<br />\
    <img src="styles/legend/Vereinfacht_0_194.png" /> San Marino<br />\
    <img src="styles/legend/Vereinfacht_0_195.png" /> Sao Tome and Principe<br />\
    <img src="styles/legend/Vereinfacht_0_196.png" /> Saudi Arabia<br />\
    <img src="styles/legend/Vereinfacht_0_197.png" /> Scarborough Reef<br />\
    <img src="styles/legend/Vereinfacht_0_198.png" /> Senegal<br />\
    <img src="styles/legend/Vereinfacht_0_199.png" /> Serranilla Bank<br />\
    <img src="styles/legend/Vereinfacht_0_200.png" /> Seychelles<br />\
    <img src="styles/legend/Vereinfacht_0_201.png" /> Siachen Glacier<br />\
    <img src="styles/legend/Vereinfacht_0_202.png" /> Sierra Leone<br />\
    <img src="styles/legend/Vereinfacht_0_203.png" /> Singapore<br />\
    <img src="styles/legend/Vereinfacht_0_204.png" /> Sint Maarten<br />\
    <img src="styles/legend/Vereinfacht_0_205.png" /> Slovakia<br />\
    <img src="styles/legend/Vereinfacht_0_206.png" /> Slovenia<br />\
    <img src="styles/legend/Vereinfacht_0_207.png" /> Solomon Islands<br />\
    <img src="styles/legend/Vereinfacht_0_208.png" /> Somalia<br />\
    <img src="styles/legend/Vereinfacht_0_209.png" /> Somaliland<br />\
    <img src="styles/legend/Vereinfacht_0_210.png" /> South Africa<br />\
    <img src="styles/legend/Vereinfacht_0_211.png" /> South Georgia and South Sandwich Islands<br />\
    <img src="styles/legend/Vereinfacht_0_212.png" /> South Korea<br />\
    <img src="styles/legend/Vereinfacht_0_213.png" /> South Sudan<br />\
    <img src="styles/legend/Vereinfacht_0_214.png" /> Spain<br />\
    <img src="styles/legend/Vereinfacht_0_215.png" /> Spratly Islands<br />\
    <img src="styles/legend/Vereinfacht_0_216.png" /> Sri Lanka<br />\
    <img src="styles/legend/Vereinfacht_0_217.png" /> Sudan<br />\
    <img src="styles/legend/Vereinfacht_0_218.png" /> Suriname<br />\
    <img src="styles/legend/Vereinfacht_0_219.png" /> Swaziland<br />\
    <img src="styles/legend/Vereinfacht_0_220.png" /> Sweden<br />\
    <img src="styles/legend/Vereinfacht_0_221.png" /> Switzerland<br />\
    <img src="styles/legend/Vereinfacht_0_222.png" /> Syria<br />\
    <img src="styles/legend/Vereinfacht_0_223.png" /> Taiwan<br />\
    <img src="styles/legend/Vereinfacht_0_224.png" /> Tajikistan<br />\
    <img src="styles/legend/Vereinfacht_0_225.png" /> Thailand<br />\
    <img src="styles/legend/Vereinfacht_0_226.png" /> The Bahamas<br />\
    <img src="styles/legend/Vereinfacht_0_227.png" /> Togo<br />\
    <img src="styles/legend/Vereinfacht_0_228.png" /> Tonga<br />\
    <img src="styles/legend/Vereinfacht_0_229.png" /> Trinidad and Tobago<br />\
    <img src="styles/legend/Vereinfacht_0_230.png" /> Tunisia<br />\
    <img src="styles/legend/Vereinfacht_0_231.png" /> Turkey<br />\
    <img src="styles/legend/Vereinfacht_0_232.png" /> Turkmenistan<br />\
    <img src="styles/legend/Vereinfacht_0_233.png" /> Turks and Caicos Islands<br />\
    <img src="styles/legend/Vereinfacht_0_234.png" /> Tuvalu<br />\
    <img src="styles/legend/Vereinfacht_0_235.png" /> Uganda<br />\
    <img src="styles/legend/Vereinfacht_0_236.png" /> Ukraine<br />\
    <img src="styles/legend/Vereinfacht_0_237.png" /> United Arab Emirates<br />\
    <img src="styles/legend/Vereinfacht_0_238.png" /> United Kingdom<br />\
    <img src="styles/legend/Vereinfacht_0_239.png" /> United Republic of Tanzania<br />\
    <img src="styles/legend/Vereinfacht_0_240.png" /> United States Minor Outlying Islands<br />\
    <img src="styles/legend/Vereinfacht_0_241.png" /> United States of America<br />\
    <img src="styles/legend/Vereinfacht_0_242.png" /> United States Virgin Islands<br />\
    <img src="styles/legend/Vereinfacht_0_243.png" /> Uruguay<br />\
    <img src="styles/legend/Vereinfacht_0_244.png" /> US Naval Base Guantanamo Bay<br />\
    <img src="styles/legend/Vereinfacht_0_245.png" /> Uzbekistan<br />\
    <img src="styles/legend/Vereinfacht_0_246.png" /> Vanuatu<br />\
    <img src="styles/legend/Vereinfacht_0_247.png" /> Vatican<br />\
    <img src="styles/legend/Vereinfacht_0_248.png" /> Venezuela<br />\
    <img src="styles/legend/Vereinfacht_0_249.png" /> Vietnam<br />\
    <img src="styles/legend/Vereinfacht_0_250.png" /> Wallis and Futuna<br />\
    <img src="styles/legend/Vereinfacht_0_251.png" /> Western Sahara<br />\
    <img src="styles/legend/Vereinfacht_0_252.png" /> Yemen<br />\
    <img src="styles/legend/Vereinfacht_0_253.png" /> Zambia<br />\
    <img src="styles/legend/Vereinfacht_0_254.png" /> Zimbabwe<br />\
    <img src="styles/legend/Vereinfacht_0_255.png" /> <br />'
        });

lyr_Vereinfacht_0.setVisible(true);
var layersList = [lyr_Vereinfacht_0];
lyr_Vereinfacht_0.set('fieldAliases', {'ADMIN': 'ADMIN', 'ISO_A3': 'ISO_A3', });
lyr_Vereinfacht_0.set('fieldImages', {'ADMIN': 'TextEdit', 'ISO_A3': 'TextEdit', });
lyr_Vereinfacht_0.set('fieldLabels', {'ADMIN': 'header label', 'ISO_A3': 'no label', });
lyr_Vereinfacht_0.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});